-- 用户与权限管理相关表
CREATE TABLE IF NOT EXISTS UserAccount (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    FullName VARCHAR(100),
    Email VARCHAR(150),
    Phone VARCHAR(50),
    PasswordHash VARCHAR(255) NOT NULL,
    IsActive TINYINT(1) NOT NULL DEFAULT 1,
    IsSuperAdmin TINYINT(1) NOT NULL DEFAULT 0,
    FailedLoginAttempts INT NOT NULL DEFAULT 0,
    LockedUntil DATETIME NULL,
    LastLoginAt DATETIME NULL,
    LastLoginIP VARCHAR(64),
    CreatedBy VARCHAR(50),
    UpdatedBy VARCHAR(50),
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_username (Username),
    INDEX idx_email (Email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Role (
    RoleID INT AUTO_INCREMENT PRIMARY KEY,
    RoleName VARCHAR(100) NOT NULL UNIQUE,
    Description VARCHAR(255),
    IsSystemRole TINYINT(1) NOT NULL DEFAULT 0,
    CreatedBy VARCHAR(50),
    UpdatedBy VARCHAR(50),
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Permission (
    PermissionID INT AUTO_INCREMENT PRIMARY KEY,
    PermissionCode VARCHAR(100) NOT NULL UNIQUE,
    ModuleName VARCHAR(100) NOT NULL,
    DisplayName VARCHAR(150) NOT NULL,
    Description VARCHAR(255),
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_module (ModuleName)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS UserRole (
    UserRoleID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    RoleID INT NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_user_role (UserID, RoleID),
    CONSTRAINT fk_userrole_user FOREIGN KEY (UserID) REFERENCES UserAccount(UserID) ON DELETE CASCADE,
    CONSTRAINT fk_userrole_role FOREIGN KEY (RoleID) REFERENCES Role(RoleID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS RolePermission (
    RolePermissionID INT AUTO_INCREMENT PRIMARY KEY,
    RoleID INT NOT NULL,
    PermissionID INT NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_role_permission (RoleID, PermissionID),
    CONSTRAINT fk_rolepermission_role FOREIGN KEY (RoleID) REFERENCES Role(RoleID) ON DELETE CASCADE,
    CONSTRAINT fk_rolepermission_permission FOREIGN KEY (PermissionID) REFERENCES Permission(PermissionID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS AuditLog (
    AuditID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NULL,
    UsernameSnapshot VARCHAR(100),
    ActionCode VARCHAR(100) NOT NULL,
    ActionName VARCHAR(150),
    TargetType VARCHAR(100),
    TargetID VARCHAR(100),
    RequestMethod VARCHAR(10),
    RequestPath VARCHAR(255),
    RequestPayload LONGTEXT,
    ClientIP VARCHAR(64),
    UserAgent VARCHAR(255),
    Remark VARCHAR(255),
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_action_code (ActionCode),
    INDEX idx_target (TargetType, TargetID),
    INDEX idx_created_at (CreatedAt),
    CONSTRAINT fk_auditlog_user FOREIGN KEY (UserID) REFERENCES UserAccount(UserID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


